/**
 * Solana mint address -> CoinMarketCap unified cryptoasset id (string).
 * Generated by scripts/generate-cmc-unified-cryptoasset-map.mjs from live
 * GET /api/v1/cmc/assets + optional CMC Pro map + public CMC detail (slug) API.
 * Re-run the script after new pools/tokens appear (set CMC_PRO_API_KEY for
 * full coverage from pro-api.coinmarketcap.com /v1/cryptocurrency/map).
 */
export const CMC_UNIFIED_CRYPTOASSET_ID_BY_MINT: Record<string, string> = {
  '1zJX5gRnjLgmTpq5sVwkq69mNDQkCemqoasyjaPW6jm': '',
  '31k88G5Mq7ptbRDf3AM13HAq6wRQHXHikR8hik7wPygk': '25241',
  '3dQTr7ror2QPKQ3GbBCokJUmjErGg8kTJzdnYjNfvi3Z': '2499',
  '4sWNB8zGWHkh6UnmwiEtzNxL4XrN7uK9tosbESbJFfVs': '',
  '6r7rgqYrdEXrYrTT3bUdefJE7woHBNsWF7c8gkmFqdev': '',
  '7h9AsF1477kb9ao5L7uhebRWaxqgyVH1UEy15asQBAGS': '',
  '98sMhvDwXj1RQi5c5Mndm3vPe9cBqPrbLaufMXFNMh5g': '',
  '9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump': '33597',
  'ARdfVeUNyeHRiKgmUTHVvn2Xpvf8ha4DtzrX5cRyQSPk': '',
  'AymATz4TCL9sWNEEV9Kvyz45CHVhDZ6kUgjTJPzLpU9P': '',
  'BANKJmvhT8tiJRsBSS1n2HryMBPvT5Ze4HU95DUAmeta': '38881',
  'BULKoNSGzxtCqzwTvg5hFJg8fx6dqZRScyXe5LYMfxrn': '',
  'C5sEDrJBTpg8YoK2pirey8gzjB78G91YNamVSrABGspK': '',
  'CARDSccUMFKoPRZxt5vt3ksUbxEFEcnZ3H2pd3dKxYjp': '38283',
  'D4FeaXPt7ZQTH5bYkLzFpyamFER4ZGue6F4tuC6fZspk': '',
  'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v': '3408',
  'Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB': '825',
  'FAFxVxnkzZHMCodkWyoccgUNgVScqMw2mhhQBYDFjFAF': '',
  'G7vQWurMkMMm2dU3iZpXYFTHT9Biio4F4gZCrwFpKNwG': '19765',
  'GDfnEsia2WLAW5t8yx2X5j2mkfA74i5kwGdDuZHt7XmG': '25714',
  'GVvPZpC6ymCoiHzYJ7CWZ8LhVn9tL2AUpRjSAsLh6jZC': '',
  'H74CYmXgMkYHYuSRsZt6RJb4NYp2u72Vw8BS5huApump': '',
  'J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn': '22533',
  'JuprjznTrTSp2UFa3ZBUFgwdAmtZCq4MQCwysN55USD': '39582',
  'LABSh5DTebUcUbEoLzXKCiXFJLecDFiDWiBGUU1GpxR': '',
  'LYLikzBQtpa9ZgVrJsqYGQpR3cC1WMJrBHaXGrQmeta': '39037',
  'METAwkXcqyXKy1AtsSgJ8JiUHwGCafnZL38n3vYmeta': '38146',
  'PRVT6TB7uss3FrUd2D9xs2zqDBsa3GbMJMwCQsgmeta': '39036',
  'So11111111111111111111111111111111111111112': '5426',
  'SoLo9oxzLDpcq1dpqAgMwgce5WqkRDtNXK7EPnbmeta': '39105',
  'StargWr5r6r8gZSjmEKGZ1dmvKWkj79r2z1xqjFstar': '',
  'cbbtcf3aa214zXHbiAZQwf4122FBYbraNdFqgw4iMij': '32994',
  'jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL': '28541',
  'kySo1nETpsZE2NWe5vj2C64mPSciH1SppmHb4XieQ7B': '',
  'omfgRBnxHsNJh6YeGbGAmWenNkenzsXyBXm3WDhmeta': '38139',
  'oreoU2P8bN6jkk3jbaiVxYnG1dCXcYxwhwyK9jSybcp': '32782',
  'sTorERYB6xAZ1SSbwpK3zoK2EEwbBrc7TZAzg1uCGiH': '',
  'y6qTpA6VMXiZfqxcBkyaMSUACXi7LG73sbe6oYspArK': '',
  'zBTCug3er3tLyffELcvDNrKkCymbPWysGcWihESYfLg': '',
};
